# Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Building Stacktree with Gradle
      run: gradle --stacktrace 
    - name: Building Info with Gradle
      run: gradle --info
    - name: Building Debug with Gradle
      run: gradle --debug
